### ISSUE TITLE
Rebuild documentation

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop-documentation#10]
Could you please regenerate the documentation to integrate the new JSDoc? And also it would be cool to have a CI that rebuilds it for each commit :eyes:

**Comment by 4ian** [comment]
Yes yes I was thinking about this, will rebuild it :)

**Comment by 4ian** [comment]
@arthuro555 Unfortunately, the usage of & in the types of JSDoc breaks JSDoc generation :/

**Comment by arthuro555** [comment]
Ok, we need to use typescript to inherit then I guess. But this is weird as this is part of the syntax.

**Comment by arthuro555** [comment]
What do you use to generate the jsdoc so I can do tests?

**Comment by 4ian** [comment]
JSDoc is not following Typescript annotations: https://github.com/Microsoft/TypeScript/issues/20077#issuecomment-531657492

It's following Google Closure Compiler types and won't support intersection types: https://github.com/jsdoc/jsdoc/issues/1285#issuecomment-279897531

Fortunately, someone made a plugin for us to use: https://github.com/chriseaton/jsdoc-plugin-intersection 

Also seems like adding @type to all members made them appear in JSDoc. I used another plugin jsdoc-autoprivate to mark them automatically as private because adding @private everywhere will really impact badly the source readability. We've been lucky to have these two plugins 🙏

> What do you use to generate the jsdoc so I can do tests?

See GDevelop/scripts/GenerateAllDocs.sh - either Doxygen for C++ or jsdoc with a few parameters for GDJS:
`jsdoc -c docs/jsdoc.conf.json -t docs/jaguarjs-jsdoc docs/DocMainPage.md`

**Comment by 4ian** [comment]
Alright it works! 

https://docs.gdevelop-app.com
https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/index.html

There is a cron to trigger a build with CircleCI every few hours. This took me a large part of the evening to fight with CircleCI to get this working but this is now done.

There is a bit of cleaning to do and would be a good idea to organize classes a bit maybe, I've not checked but I guess there is way to do that in JSDoc options/templates/annotations :)
This means we have to be a bit careful when using type annotations, some might not be supported by JSDoc unfortunately.

I'll see to add to the CI tests in GDevelop a run of the documentation generator to be sure we're not breaking it.

**Comment by arthuro555** [comment]
Wow, you managed to do it? Amazing! And you also made an hourly build? Just wow.

**Comment by arthuro555** [comment]
Documentation is 404 @4ian

**Comment by 4ian** [comment]
Oops, forgot a file that got erased when publishing. Fixed now!
